/* Generated By:JavaCC: Do not edit this line. BelaConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int APAR = 6;
  /** RegularExpression Id. */
  int FPAR = 7;
  /** RegularExpression Id. */
  int ACHAVES = 8;
  /** RegularExpression Id. */
  int FCHAVES = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int PVIRGULA = 11;
  /** RegularExpression Id. */
  int TIPOFLOAT = 12;
  /** RegularExpression Id. */
  int TIPOBOOL = 13;
  /** RegularExpression Id. */
  int TIPOVOID = 14;
  /** RegularExpression Id. */
  int ATRIBUICAO = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int readInput = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int PRINTLN = 21;
  /** RegularExpression Id. */
  int OPMAIS = 22;
  /** RegularExpression Id. */
  int OPMENOS = 23;
  /** RegularExpression Id. */
  int OPMULT = 24;
  /** RegularExpression Id. */
  int OPDIV = 25;
  /** RegularExpression Id. */
  int OPE = 26;
  /** RegularExpression Id. */
  int OPOU = 27;
  /** RegularExpression Id. */
  int OPMENOR = 28;
  /** RegularExpression Id. */
  int OPMAIOR = 29;
  /** RegularExpression Id. */
  int OPIGUAL = 30;
  /** RegularExpression Id. */
  int VIRGULA = 31;
  /** RegularExpression Id. */
  int FUNCAO = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int ID = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"var\"",
    "\";\"",
    "\"float\"",
    "\"bool\"",
    "\"void\"",
    "\"=\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"readInput\"",
    "\"return\"",
    "\"printLn\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"fun\"",
    "<NUM>",
    "<ID>",
  };

}
